import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Recipe Blog",
  description: "generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let header = (
    <header className={cn(
      "w-full max-w-800 m-auto my-2 pl-10 flex h-20 items-center space-x-1 rounded-base border-2 border-border bg-main"
    )}>
      <Link href='/'>
        <h1 className="text-3xl font-bold">Recipe Blog Name</h1>
      </Link>
    </header>
  )

  let footer = (
    <footer
    className={cn(
      "w-full max-w-800 m-auto flex items-center justify-center pt-8"
    )}>
      km, 2025
    </footer>
  )

  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
