import type { Metadata } from "next";
import "./globals.css";
import Navbar from './../components/Navbar';
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Cindy's Cookbook",
  description: "generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let footer = (
    <footer
    className={cn(
      "w-full max-w-800 m-auto flex items-center justify-center pt-8"
    )}>
      km, 2025
    </footer>
  )

  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        {footer}
      </body>
    </html>
  );
}
