import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Recipe Blog",
  description: "generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let header = (
    <header>
      <Link href='/'>
        <h1>Recipe Blog Name</h1>
      </Link>
    </header>
  )

  let footer = (
    <footer>
      km, 2025
    </footer>
  )

  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
